name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Alembic migrate (temp DB)
        env:
          SQLITE_PATH: ${{ runner.temp }}/ci.db
        run: |
          export PYTHONPATH="$PWD"
          alembic upgrade head

      - name: Run tests
        env:
          SQLITE_PATH: ${{ runner.temp }}/ci.db
        run: |
          pytest -q
