name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r  C:\Users\user\Downloads\ai_study_buddy\requirements.txt
      - name: Run tests
        run: |
          pytest -q ai_study_buddy/tests